[package]
name = "aoc2021"
version = "0.1.0"
edition = "2021"
authors = ["Steven Hunt <sph@shunty.co.uk>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
